### ISSUE TITLE
Promise 생성자 안에 async 넣는 부분에 대한 Eslint 질문 입니다 🙌

### ISSUE THREAD

**Issue by rlwi440** [HeropCode/Vue-Movie-app#22]
````
fetchMovies({state,commit},pageNum){
      return new Promise(async resolve => {
        const res= await axios.get(`http://www.omdbapi.com/?apikey=6f3b4914&s=${state.title}&page=${pageNum}`)
        commit('pushIntoMovies',res.data.Search)
        resolve(res.data)
      })
````
강의를 보다가 질문을 드립니다 
promise 생성자 안에 async 넣는과정에서 eslint 7 버전 에서는  규칙에 어긋난다고 구글에 검색해보니 나오는것 같더라구요 
그래서 저는 현재 버전을 
 
eslint: "^5.16.0", eslint-plugin-vue": "^5.2.3" 

  낮춰서 강의를 듣고있습니다  
버전을 낮춰서 들어도 상관이 없는지 궁금합니다. 아니면 또 다른 방법이 있는지 궁금합니다 .^^
좋은강의 해주셔서 정말 감사합니다 🙌

````
Promise executor functions should not be async (no-async-promise-executor) at src\store\movie.js:25:32:
````

**Comment by ParkYoungWoong** [comment]
@rlwi440 안녕하세요.
관련해서 예전에 질문 받은 적이 있어서 링크를 남기니 확인해 보세요.
https://github.com/HeropCode/Vue-Movie-app/issues/9#issuecomment-737573133

참고로 패키지 버전은 얼마든지 낮춰서 사용하셔도 됩니다.
전혀 문제가 없습니다.
간혹 기타 이슈가 있는 패키지 버전이 있을 수 있는데요.
중요한 로직을 다루는 패키지가 아니면 상관없습니다.

위 링크 이슈 내용 확인해 보시고,
혹시 다른 질문이나 이슈 있으면 알려주세요~
좋은 하루 보내세요~😆

**Comment by rlwi440** [comment]
감사합니다 ^^ 좋은 명강의 해주셔서  감사합니다 좋은 하루보내세요 ~~😁
